# version: '3'

volumes:
  cronjobs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .

x-common: &default-build
  build:
    context: .

services:
  bas_cronjobs:
    container_name: bas_cronjobs
    ports:
      - 4567:4567
    restart: always
    <<: *default-build
    volumes:
      - cronjobs:/app
    command: ["bash", "/app/scripts/update_container.sh"]
    deploy:
      resources:
        limits:
          memory: 100M
