# version: '3'

volumes:
  cronjobs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .

x-common: &default-build
  build:
    context: .

services:
  bas_cronjobs:
    container_name: bas_cronjobs
    restart: always
    <<: *default-build
    volumes:
      - cronjobs:/app
    command: [ "bash", "/app/scripts/update_container.sh" ]
    deploy:
      resources:
        limits:
          memory: 100M

  whatsapp-bot:
    container_name: whatsapp_bot
    restart: always
    <<: *default-build
    volumes:
      - .env:/app/.env
      - ./whatsapp:/app
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
    ports:
      - 4567:4567
    env_file:
      - .env
    command: [ "bash", "/app/scripts/update_container.sh" ]
    deploy:
      resources:
        limits:
          memory: 100M
