# version: '3'

volumes:
  pgdata:
    driver: local
  cronjobs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .

networks:
  bas_network:
    driver: bridge
    name: bas_network

services:
  bas_db:
    image: postgres:13-alpine
    container_name: bas_db
    restart: unless-stopped
    networks:
      - bas_network
    ports:
      - 8001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 50M

  bas_cronjobs:
    container_name: bas_cronjobs
    restart: always
    build: .
    volumes:
      - cronjobs:/app
    env_file:
      - .env
    depends_on:
      - bas_db
    networks:
      - bas_network
    command: ["bash", "/app/scripts/update_container.sh"]
    deploy:
      resources:
        limits:
          memory: 460M
