volumes:
  grafana-storage:
    driver: local

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
