#!/bin/bash

# Absolute path to the directory containing the use cases execution
SCRIPTS_DIR="/app/src/execution"
RUBY_PATH="/usr/local/bundle"

# Environment variables
ENV_VARS=(
    # RUBY CONFIG
    "PATH=$PATH"
    "GEM_HOME=$RUBY_PATH"
    "GEM_PATH=$RUBY_PATH"

    # DATABASE
    "DB_HOST=$DB_HOST"
    "DB_PORT=$DB_PORT"
    "POSTGRES_DB=$POSTGRES_DB"
    "POSTGRES_USER=$POSTGRES_USER"
    "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"

    # BOT NAME
    "DISCORD_BOT_NAME=$DISCORD_BOT_NAME"

    # NOTION
    "NOTION_SECRET=$NOTION_SECRET"

    # BIRTHDAY
    "BIRTHDAY_NOTION_DATABASE_ID=$BIRTHDAY_NOTION_DATABASE_ID"
    "BIRTHDAY_DISCORD_WEBHOOK=$BIRTHDAY_DISCORD_WEBHOOK"
    "NEXT_WEEK_BIRTHDAY_DISCORD_WEBHOOK=$NEXT_WEEK_BIRTHDAY_DISCORD_WEBHOOK"

    # PTO
    "PTO_NOTION_DATABASE_ID=$PTO_NOTION_DATABASE_ID"
    "OPENAI_SECRET=$OPENAI_SECRET"
    "PTO_OPENAI_ASSISTANT=$PTO_OPENAI_ASSISTANT"
    "NEXT_WEEK_PTO_OPENAI_ASSISTANT=$NEXT_WEEK_PTO_OPENAI_ASSISTANT"
    "PTO_DISCORD_WEBHOOK=$PTO_DISCORD_WEBHOOK"
    "NEXT_WEEK_PTO_DISCORD_WEBHOOK=$NEXT_WEEK_PTO_DISCORD_WEBHOOK"

    # WIP LIMIT
    "WIP_COUNT_NOTION_DATABASE_ID=$WIP_COUNT_NOTION_DATABASE_ID"
    "WIP_LIMIT_NOTION_DATABASE_ID=$WIP_LIMIT_NOTION_DATABASE_ID"
    "WIP_LIMIT_DISCORD_WEBHOOK=$WIP_LIMIT_DISCORD_WEBHOOK"

    # SUPPORT ERMAIL
    "SUPPORT_EMAIL_ACCOUNT=$SUPPORT_EMAIL_ACCOUNT"
    "SUPPORT_EMAIL_REFRESH_TOKEN=$SUPPORT_EMAIL_REFRESH_TOKEN"
    "SUPPORT_EMAIL_CLIENT_ID=$SUPPORT_EMAIL_CLIENT_ID"
    "SUPPORT_EMAIL_CLIENT_SECRET=$SUPPORT_EMAIL_CLIENT_SECRET"
    "SUPPORT_EMAIL_INBOX=$SUPPORT_EMAIL_INBOX"
    "SUPPORT_EMAIL_RECEPTOR=$SUPPORT_EMAIL_RECEPTOR"
    "SUPPORT_EMAIL_DISCORD_WEBHOOK=$SUPPORT_EMAIL_DISCORD_WEBHOOK"

    # REVIEW IMAGES
    "REVIEW_IMAGE_OPENAI_ASSISTANT=$REVIEW_IMAGE_OPENAI_ASSISTANT"

    # DIGITAL OCEAN BILLING ALERT
    "DIGITAL_OCEAN_SECRET=$DIGITAL_OCEAN_SECRET"
    "DIGITAL_OCEAN_THRESHOLD=$DIGITAL_OCEAN_THRESHOLD"
    "DIGITAL_OCEAN_DISCORD_WEBHOOK=$DIGITAL_OCEAN_DISCORD_WEBHOOK"

    # WEB AVAILABILITY
    "WEBSITES_AVAILABILITY_NOTION_DATABASE_ID=$WEBSITES_AVAILABILITY_NOTION_DATABASE_ID"
    "WEBSITES_AVAILABILITY_DISCORD_WEBHOOK=$WEBSITES_AVAILABILITY_DISCORD_WEBHOOK"

    # OSPO MAINTENANCE
    "OSPO_MAINTENANCE_SECRET=$OSPO_MAINTENANCE_SECRET"
    "OSPO_MAINTENANCE_APP_ID=$OSPO_MAINTENANCE_APP_ID"
    "OSPO_MAINTENANCE_NOTION_DATABASE_ID=$OSPO_MAINTENANCE_NOTION_DATABASE_ID"
    "OSPO_MAINTENANCE_NOTION_USERS_DATABASE_ID=$OSPO_MAINTENANCE_NOTION_USERS_DATABASE_ID"
)

# Temporary file to store the new crontab
TEMP_CRONTAB=$(mktemp)

# Add environment variables to the crontab file
for ENV_VAR in "${ENV_VARS[@]}"
do
    echo "$ENV_VAR" >> $TEMP_CRONTAB
done

# Iterate over each folder in the base directory
for folder in "$SCRIPTS_DIR"/*; do
  # Check if it is a directory
  if [ -d "$folder" ]; then
    # Check if schedules.sh exists and is executable
    if [ -x "$folder/schedules.sh" ]; then
      echo "Executing schedules.sh in $folder"
      # Execute the script
      "$folder/schedules.sh" >> $TEMP_CRONTAB
    else
      echo "schedules.sh not found or not executable in $folder"
    fi
  fi
done

# Install the new crontab
crontab $TEMP_CRONTAB

# Clean up
rm $TEMP_CRONTAB

cron -f
